# Generated by Django 2.0 on 2018-01-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vampire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vampire_clan', models.CharField(choices=[('BH', 'Brujah'), ('GL', 'Gangrel'), ('MN', 'Malkavian'), ('NU', 'Nosferatu'), ('TR', 'Toreador'), ('TE', 'Tremere'), ('VE', 'Ventrue'), ('CF', 'Caitiff')], default='CF', max_length=2)),
                ('sect', models.CharField(choices=[('AH', 'Anarch'), ('CA', 'Camarilla'), ('ST', 'Sabat')], default='CA', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charactermanager.Player')),
            ],
        ),
    ]
